version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - deploy_kingtide_default
    restart: always

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3030:3030"
    networks:
      - deploy_kingtide_default
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:password@deportes-db:5432/postgres?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - deploy_kingtide_default
    restart: always

volumes:
  grafana_data:
    driver: local

networks:
  deploy_kingtide_default:
    external: true
