global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['146.190.123.90:9100']  # Para métricas del servidor

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']  # Nombre del contenedor

  - job_name: 'docker_services'
    static_configs:
      - targets:
          - 'api_deportes:8000'
          - 'frontend_kingtide:8080'
          - 'api_clima:3000'
          - 'deportes-db:5432'
